base_config:
  - configs/singing/fs2.yaml
  - usr/configs/m4singer/base.yaml
task_cls: usr.diffsinger_task.AuxDecoderMIDITask

max_frames: 5000
max_tokens: 40000
rel_pos: true

use_pitch_embed: false
num_valid_plots: 10
max_updates: 320000
lr: 1
max_sentences: 12
save_gt: true
pe_enable: true
